### ISSUE TITLE
How to use css-groundhog stylings & Theming

### ISSUE THREAD

**Issue by thomaspink** [Dynatrace/ngx-groundhog#14]
- Use the existing one in css-groundhog
- Define new ones in core
- ...

Usage:
https://github.com/Dynatrace/ngx-groundhog/blob/master/src/lib/button/button.scss#L1

cc @tomheller @ffriedl89

**Comment by ffriedl89** [comment]
## proposal: 
move shared code parts (css-groundhog, ngx-groundhog) to <comp>-common style file with mixins

e.g. btn-common.scss
### css-groundhog
.btn-common.scss
```scss
@mixin btn-common {
  background-color: $green-100;
}
```
btn.scss
```scss
@import 'btn-common'
.btn {
  @include btn-common()
}
```

### ngx-groundhog

button.scss
```scss
@import '@dynatrace/css-groundhog/button/btn-common'
.gh-button {
  @include btn-common()
}
```

**Comment by thomaspink** [comment]
@katrin-freihofner pls implement a prototype using the button component tomorrow.
Let's also include scss into core

**Comment by katrin-freihofner** [comment]
We agreed on the following theming logic/structure:

Every Component must have a `<name>-theme.scss` in addition to the base `<name>.scss` file.
There is also a core component that should handle all core styling (see `lib/core/styles` & `lib/core/core.scss`).
Themes are defined in the theming directory in the core. Additionally we should provide a theme that includes all themes (should be used when more than one theme is required in an application)

Components:
- `lib/button/button.scss` - basic styling for button component
- `lib/button/button-theme.scss` - theme dependent styling for button component. must expose a mixin named `gh-button-theme($theme)`

Core
- `lib/core/core.scss` Imports core stylings from `@dynatrace/css-groundhog` add additional (if needed) core styles
- `lib/core/_someglobalstyling.scss`
- `lib/core/theming` includes various logic for theming
- `lib/core/theming/prebuilt` defines prebuilt themes (including an all-themes theme)

**Comment by thomaspink** [comment]
As discussed, we removed css-groundhog dependency completely.
